export default [
{
    id:1,
    img1:require('../../../assets/img/test.png'),
    img2:require('../../../assets/img/test.png'),
    img3:require('../../../assets/img/test.png'),
    img4:require('../../../assets/img/test.png'),
    img5:require('../../../assets/img/test.png'),
    img6:require('../../../assets/img/test.png'),
    title: 'Découvrez des' ,
    titleBr: 'endroits magnifiques',
    subtitle:'Lorem ipsum dolor sit amet, consectetur',
    subtitleBr: 'adipiscing elit, sed do eiusmod tempor',
},{
    id:2,
    img1:require('../../../assets/img/test.png'),
    img2:require('../../../assets/img/test.png'),
    img3:require('../../../assets/img/test.png'),
    img4:require('../../../assets/img/test.png'),
    img5:require('../../../assets/img/test.png'),
    img6:require('../../../assets/img/test.png'),
    title: 'Profitez des restaurants' ,
    titleBr: 'selon votre gôut',
    subtitle:'Lorem ipsum dolor sit amet, consectetur',
    subtitleBr: 'adipiscing elit, sed do eiusmod tempor',
},{
    id:3,
    img1:require('../../../assets/img/test.png'),
    img2:require('../../../assets/img/test.png'),
    img3:require('../../../assets/img/test.png'),
    img4:require('../../../assets/img/test.png'),
    img5:require('../../../assets/img/test.png'),
    img6:require('../../../assets/img/test.png'),
    title: 'Let’s play and be happy !' ,
    titleBr: '',
    subtitle:'Lorem ipsum dolor sit amet, consectetur',
    subtitleBr: 'adipiscing elit, sed do eiusmod tempor',
}
]